services:
  api-gateway:
    image: nginx
    container_name: microservices
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
      - review-service

  user-service:
    build: ../user-service
    container_name: user-service
    ports:
      - "3001:3001"
  
  product-service:
    build: ../product-service
    container_name: product-service
    ports:
      - "3002:3002"

  order-service:
    build: ../order-service
    container_name: order-service
    ports:
      - "3003:3003"

  payment-service:
    build: ../payment-service
    container_name: payment-service
    ports:
      - "3004:3004"

  review-service:
    build: ../review-service
    container_name: review-service
    ports:
      - "3005:3005"